language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install --upgrade pytest

script:
  - python -m pytest --cov=openet

after_success:
  - codecov
